cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 30 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 31 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 32 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 33 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 34 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 35 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 36 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 37 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 38 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 39 -c 100 & 
