cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 10 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 11 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 12 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 13 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 14 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 15 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 16 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 17 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 18 -c 100 & 
cd /home/ubuntu/newOrgan/nodes; python3 client.py -i 19 -c 100 & 
